
import './globals.css'
import Link from 'next/link'


export const metadata = {
  title: 'Next App - First Step',
  description: 'Generated by itslitulinchpin2',
}

export default function RootLayout({ children }) {
  return (
    <html >
      <body >
        
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li>
        </ol>
        
        {children}
        
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="Delete"></input></li>
        </ul>
        </body>
    </html>
  )
}
