import { Control } from './Control';
import './globals.css'
import Link from 'next/link'


export const metadata = {
  title: 'Next App - First Step',
  description: 'Generated by itslitulinchpin2',
}

export default async function RootLayout({ children }) {
 
    
      const resp = await fetch('http://localhost:9999/topics', {cache:"no-store"});
      const topics = await resp.json();

  return (
    <html >
      <body >
        
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((data)=>{
           return <li key={data.id}><Link href={`/read/${data.id}`}>{data.title}</Link></li>
          })}
        
        </ol>
        
        {children}
        
        <Control></Control>
        
        </body>
    </html>
  )
}
